### ISSUE TITLE
Software vulnerability due to CVE-2016-6501

### ISSUE THREAD

**Issue by vincentfree** [JFrogDev/artifactory-client-java#146]
# artifactory-client-java suffers from LDAP entry poisoning
[CVE](https://nvd.nist.gov/vuln/detail/CVE-2016-6501) explains what the problem is.

At the company where i work we can't release software with CVE's above the rating of 7.5 so this problem blocks our release. 

CVE discovered by OWASP

**Comment by markgalpin** [comment]
This issue was fixed before it was announced, thanks to a responsible security researcher discussing it with us.  Please upgrade to artifactory 4.11 or later, as per the CVE, and the issue will be fully addressed.  In general I would recommend upgrading out to 5.4.6, but if you can't upgrade to 5.x, 4.16.1 is a good choice as well.

**Comment by vincentfree** [comment]
Thank you for the information, I will communicate this within the company I work for.
