### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by zonArt** [JFrogDev/artifactory-client-java#181]
Hi,

It has been a while since last release. When do you plan the next one ? I'm waiting for the latest feature to use in one of my project. Thank you in advance.

Best Regards,

**Comment by eyalbe4** [comment]
@zonArt,
The upcoming release includes massive changes in the client. Among those changes are: we replaced the groovy HttpBuilder with a native Apache HttpClient,  replaced many of the groovy classes with java and added improvements. The RestCall API has also been improved.
Due to the massive changes, some APIs, specifically the RestCall, are modified in the new release.
Before releasing, we wanted to make sure that a few of our internal projects use the new plugin code for a while. We are planning to release soon through.

**Comment by zonArt** [comment]
@eyalbe4 
Thank you very much for this clear explanation, I fully understand your point and I'm looking forward to getting the next release. Thanks for the good job
